// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using saas.Data;

#nullable disable

namespace saas.Migrations
{
    [DbContext(typeof(SaasDbContext))]
    [Migration("20260824225033_AgregarConfiguracionEmpresa")]
    partial class AgregarConfiguracionEmpresa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("saas.Models.Caja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FondoFijo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("PermiteTurnos")
                        .HasColumnType("bit");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EmpresaId", "Nombre");

                    b.ToTable("Cajas");
                });

            modelBuilder.Entity("saas.Models.CajaMedioPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CajaId")
                        .HasColumnType("int");

                    b.Property<int>("MedioPagoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedioPagoId");

                    b.HasIndex("CajaId", "MedioPagoId")
                        .IsUnique();

                    b.ToTable("CajaMediosPago");
                });

            modelBuilder.Entity("saas.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("saas.Models.CategoriaGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EmpresaId", "Nombre");

                    b.ToTable("CategoriasGasto");
                });

            modelBuilder.Entity("saas.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Documento")
                        .IsUnique()
                        .HasFilter("[Documento] IS NOT NULL");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("saas.Models.CobroVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CajaId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MedioPagoId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TurnoCajaId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAnulacionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Fecha");

                    b.HasIndex("MedioPagoId");

                    b.HasIndex("TurnoCajaId");

                    b.HasIndex("UsuarioAnulacionId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VentaId");

                    b.ToTable("CobrosVenta");
                });

            modelBuilder.Entity("saas.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<string>("TipoComprobante")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsuarioAnulacionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("UsuarioAnulacionId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EmpresaId", "Fecha");

                    b.HasIndex("EmpresaId", "ProveedorId", "TipoComprobante", "NumeroComprobante");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("saas.Models.ConfiguracionEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cuit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<decimal>("IvaPorcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("LogoRuta")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("MontoVentaImportante")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .IsUnique();

                    b.ToTable("ConfiguracionesEmpresa");
                });

            modelBuilder.Entity("saas.Models.DetalleCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CompraId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioCostoAnterior")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrecioVentaAnterior")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrecioVentaNuevo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("CompraId", "ProductoId")
                        .IsUnique();

                    b.ToTable("DetallesCompra");
                });

            modelBuilder.Entity("saas.Models.DetalleDevolucionCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("DetalleCompraId")
                        .HasColumnType("int");

                    b.Property<int>("DevolucionCompraId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DetalleCompraId");

                    b.HasIndex("DevolucionCompraId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("DevolucionCompraId", "DetalleCompraId")
                        .IsUnique();

                    b.ToTable("DetallesDevolucionCompra");
                });

            modelBuilder.Entity("saas.Models.DetalleReintegroVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("ReintegroVentaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ReintegroVentaId");

                    b.ToTable("DetallesReintegroVenta");
                });

            modelBuilder.Entity("saas.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("saas.Models.DevolucionCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompraId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsuarioAnulacionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Fecha");

                    b.HasIndex("UsuarioAnulacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DevolucionesCompra");
                });

            modelBuilder.Entity("saas.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("saas.Models.MedioPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EmpresaId", "Nombre");

                    b.ToTable("MediosPago");
                });

            modelBuilder.Entity("saas.Models.MovimientoCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CajaId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoriaGastoId")
                        .HasColumnType("int");

                    b.Property<int?>("CobroVentaId")
                        .HasColumnType("int");

                    b.Property<string>("Concepto")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Direccion")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MedioPagoId")
                        .HasColumnType("int");

                    b.Property<int?>("MovimientoOrigenId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PagoProveedorId")
                        .HasColumnType("int");

                    b.Property<int?>("ReintegroProveedorId")
                        .HasColumnType("int");

                    b.Property<int?>("ReintegroVentaId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("TransferenciaCajaId")
                        .HasColumnType("int");

                    b.Property<int?>("TurnoCajaId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaGastoId");

                    b.HasIndex("CobroVentaId")
                        .IsUnique()
                        .HasFilter("[CobroVentaId] IS NOT NULL");

                    b.HasIndex("MedioPagoId");

                    b.HasIndex("MovimientoOrigenId");

                    b.HasIndex("PagoProveedorId")
                        .IsUnique()
                        .HasFilter("[PagoProveedorId] IS NOT NULL");

                    b.HasIndex("ReintegroProveedorId")
                        .IsUnique()
                        .HasFilter("[ReintegroProveedorId] IS NOT NULL");

                    b.HasIndex("ReintegroVentaId")
                        .IsUnique()
                        .HasFilter("[ReintegroVentaId] IS NOT NULL");

                    b.HasIndex("Tipo");

                    b.HasIndex("TransferenciaCajaId");

                    b.HasIndex("TurnoCajaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("CajaId", "Fecha");

                    b.HasIndex("EmpresaId", "Fecha");

                    b.ToTable("MovimientosCaja");
                });

            modelBuilder.Entity("saas.Models.MovimientoStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("CompraId")
                        .HasColumnType("int");

                    b.Property<int?>("DevolucionCompraId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int?>("ReintegroVentaId")
                        .HasColumnType("int");

                    b.Property<int>("StockAnterior")
                        .HasColumnType("int");

                    b.Property<int>("StockPosterior")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("DevolucionCompraId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Fecha");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ReintegroVentaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VentaId");

                    b.ToTable("MovimientosStock");
                });

            modelBuilder.Entity("saas.Models.PagoProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CajaId")
                        .HasColumnType("int");

                    b.Property<int>("CompraId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MedioPagoId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TurnoCajaId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAnulacionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("CompraId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Fecha");

                    b.HasIndex("MedioPagoId");

                    b.HasIndex("TurnoCajaId");

                    b.HasIndex("UsuarioAnulacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PagosProveedor");
                });

            modelBuilder.Entity("saas.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoBarra")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioCosto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PuntoReposicion")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("UrlImagen")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EmpresaId", "CodigoBarra")
                        .IsUnique()
                        .HasFilter("[CodigoBarra] IS NOT NULL");

                    b.HasIndex("EmpresaId", "Nombre")
                        .IsUnique();

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("saas.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CUIT")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreFantasia")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EmpresaId", "CUIT");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("saas.Models.ReintegroProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CajaId")
                        .HasColumnType("int");

                    b.Property<int>("CompraId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MedioPagoId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TurnoCajaId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAnulacionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("CompraId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Fecha");

                    b.HasIndex("MedioPagoId");

                    b.HasIndex("TurnoCajaId");

                    b.HasIndex("UsuarioAnulacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ReintegrosProveedor");
                });

            modelBuilder.Entity("saas.Models.ReintegroVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CajaId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MedioPagoId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TurnoCajaId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAnulacionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Fecha");

                    b.HasIndex("MedioPagoId");

                    b.HasIndex("TurnoCajaId");

                    b.HasIndex("UsuarioAnulacionId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VentaId");

                    b.ToTable("ReintegrosVenta");
                });

            modelBuilder.Entity("saas.Models.TransferenciaCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CajaDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("CajaOrigenId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TurnoCajaId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAnulacionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CajaDestinoId");

                    b.HasIndex("CajaOrigenId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Fecha");

                    b.HasIndex("TurnoCajaId");

                    b.HasIndex("UsuarioAnulacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TransferenciasCaja");
                });

            modelBuilder.Entity("saas.Models.TurnoCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CajaId")
                        .HasColumnType("int");

                    b.Property<bool>("CierreForzado")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Diferencia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EfectivoContado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EfectivoEsperado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FondoFijoAplicado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ImporteRendido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoCierreForzado")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UsuarioAperturaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioCierreId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CajaId")
                        .IsUnique()
                        .HasFilter("[Estado] = 1");

                    b.HasIndex("Estado");

                    b.HasIndex("UsuarioAperturaId")
                        .IsUnique()
                        .HasFilter("[Estado] = 1");

                    b.HasIndex("UsuarioCierreId");

                    b.HasIndex("EmpresaId", "FechaApertura");

                    b.ToTable("TurnosCaja");
                });

            modelBuilder.Entity("saas.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenPerfil")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("saas.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EmpresaId", "Fecha");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("saas.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("saas.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("saas.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("saas.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("saas.Models.Caja", b =>
                {
                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithMany("Cajas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("saas.Models.CajaMedioPago", b =>
                {
                    b.HasOne("saas.Models.Caja", "Caja")
                        .WithMany("CajaMediosPago")
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.MedioPago", "MedioPago")
                        .WithMany("CajaMediosPago")
                        .HasForeignKey("MedioPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("MedioPago");
                });

            modelBuilder.Entity("saas.Models.Categoria", b =>
                {
                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithMany("Categorias")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("saas.Models.CategoriaGasto", b =>
                {
                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithMany("CategoriasGasto")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("saas.Models.Cliente", b =>
                {
                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithMany("Clientes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("saas.Models.CobroVenta", b =>
                {
                    b.HasOne("saas.Models.Caja", "Caja")
                        .WithMany()
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithMany("CobrosVenta")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.MedioPago", "MedioPago")
                        .WithMany("CobrosVenta")
                        .HasForeignKey("MedioPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.TurnoCaja", "TurnoCaja")
                        .WithMany()
                        .HasForeignKey("TurnoCajaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.Usuario", "UsuarioAnulacion")
                        .WithMany("CobrosVentaAnulados")
                        .HasForeignKey("UsuarioAnulacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.Usuario", "Usuario")
                        .WithMany("CobrosVenta")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Venta", "Venta")
                        .WithMany("CobrosVenta")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("Empresa");

                    b.Navigation("MedioPago");

                    b.Navigation("TurnoCaja");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioAnulacion");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("saas.Models.Compra", b =>
                {
                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithMany("Compras")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Proveedor", "Proveedor")
                        .WithMany("Compras")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Usuario", "UsuarioAnulacion")
                        .WithMany("ComprasAnuladas")
                        .HasForeignKey("UsuarioAnulacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.Usuario", "Usuario")
                        .WithMany("Compras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Proveedor");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioAnulacion");
                });

            modelBuilder.Entity("saas.Models.ConfiguracionEmpresa", b =>
                {
                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithOne("Configuracion")
                        .HasForeignKey("saas.Models.ConfiguracionEmpresa", "EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("saas.Models.DetalleCompra", b =>
                {
                    b.HasOne("saas.Models.Compra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Producto", "Producto")
                        .WithMany("DetallesCompra")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("saas.Models.DetalleDevolucionCompra", b =>
                {
                    b.HasOne("saas.Models.DetalleCompra", "DetalleCompra")
                        .WithMany("DetallesDevolucion")
                        .HasForeignKey("DetalleCompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.DevolucionCompra", "DevolucionCompra")
                        .WithMany("Detalles")
                        .HasForeignKey("DevolucionCompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DetalleCompra");

                    b.Navigation("DevolucionCompra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("saas.Models.DetalleReintegroVenta", b =>
                {
                    b.HasOne("saas.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.ReintegroVenta", "ReintegroVenta")
                        .WithMany("Detalles")
                        .HasForeignKey("ReintegroVentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("ReintegroVenta");
                });

            modelBuilder.Entity("saas.Models.DetalleVenta", b =>
                {
                    b.HasOne("saas.Models.Producto", "Producto")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("saas.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("saas.Models.DevolucionCompra", b =>
                {
                    b.HasOne("saas.Models.Compra", "Compra")
                        .WithMany("DevolucionesCompra")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Usuario", "UsuarioAnulacion")
                        .WithMany()
                        .HasForeignKey("UsuarioAnulacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioAnulacion");
                });

            modelBuilder.Entity("saas.Models.MedioPago", b =>
                {
                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithMany("MediosPago")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("saas.Models.MovimientoCaja", b =>
                {
                    b.HasOne("saas.Models.Caja", "Caja")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.CategoriaGasto", "CategoriaGasto")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("CategoriaGastoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.CobroVenta", "CobroVenta")
                        .WithOne("MovimientoCaja")
                        .HasForeignKey("saas.Models.MovimientoCaja", "CobroVentaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.MedioPago", "MedioPago")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("MedioPagoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.MovimientoCaja", "MovimientoOrigen")
                        .WithMany("Reversiones")
                        .HasForeignKey("MovimientoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.PagoProveedor", "PagoProveedor")
                        .WithOne("MovimientoCaja")
                        .HasForeignKey("saas.Models.MovimientoCaja", "PagoProveedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.ReintegroProveedor", "ReintegroProveedor")
                        .WithOne("MovimientoCaja")
                        .HasForeignKey("saas.Models.MovimientoCaja", "ReintegroProveedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.ReintegroVenta", "ReintegroVenta")
                        .WithOne("MovimientoCaja")
                        .HasForeignKey("saas.Models.MovimientoCaja", "ReintegroVentaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.TransferenciaCaja", "TransferenciaCaja")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("TransferenciaCajaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.TurnoCaja", "TurnoCaja")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("TurnoCajaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.Usuario", "Usuario")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("CategoriaGasto");

                    b.Navigation("CobroVenta");

                    b.Navigation("Empresa");

                    b.Navigation("MedioPago");

                    b.Navigation("MovimientoOrigen");

                    b.Navigation("PagoProveedor");

                    b.Navigation("ReintegroProveedor");

                    b.Navigation("ReintegroVenta");

                    b.Navigation("TransferenciaCaja");

                    b.Navigation("TurnoCaja");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("saas.Models.MovimientoStock", b =>
                {
                    b.HasOne("saas.Models.Compra", "Compra")
                        .WithMany("MovimientosStock")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.DevolucionCompra", "DevolucionCompra")
                        .WithMany("MovimientosStock")
                        .HasForeignKey("DevolucionCompraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithMany("MovimientosStock")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Producto", "Producto")
                        .WithMany("MovimientosStock")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.ReintegroVenta", "ReintegroVenta")
                        .WithMany("MovimientosStock")
                        .HasForeignKey("ReintegroVentaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.Usuario", "Usuario")
                        .WithMany("MovimientosStock")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Venta", "Venta")
                        .WithMany("MovimientosStock")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Compra");

                    b.Navigation("DevolucionCompra");

                    b.Navigation("Empresa");

                    b.Navigation("Producto");

                    b.Navigation("ReintegroVenta");

                    b.Navigation("Usuario");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("saas.Models.PagoProveedor", b =>
                {
                    b.HasOne("saas.Models.Caja", "Caja")
                        .WithMany()
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Compra", "Compra")
                        .WithMany("PagosProveedor")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithMany("PagosProveedor")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.MedioPago", "MedioPago")
                        .WithMany("PagosProveedor")
                        .HasForeignKey("MedioPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.TurnoCaja", "TurnoCaja")
                        .WithMany()
                        .HasForeignKey("TurnoCajaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.Usuario", "UsuarioAnulacion")
                        .WithMany("PagosProveedorAnulados")
                        .HasForeignKey("UsuarioAnulacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.Usuario", "Usuario")
                        .WithMany("PagosProveedor")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("Compra");

                    b.Navigation("Empresa");

                    b.Navigation("MedioPago");

                    b.Navigation("TurnoCaja");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioAnulacion");
                });

            modelBuilder.Entity("saas.Models.Producto", b =>
                {
                    b.HasOne("saas.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithMany("Productos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("saas.Models.Proveedor", b =>
                {
                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithMany("Proveedores")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("saas.Models.ReintegroProveedor", b =>
                {
                    b.HasOne("saas.Models.Caja", "Caja")
                        .WithMany()
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Compra", "Compra")
                        .WithMany("ReintegrosProveedor")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithMany("ReintegrosProveedor")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.MedioPago", "MedioPago")
                        .WithMany("ReintegrosProveedor")
                        .HasForeignKey("MedioPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.TurnoCaja", "TurnoCaja")
                        .WithMany()
                        .HasForeignKey("TurnoCajaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.Usuario", "UsuarioAnulacion")
                        .WithMany("ReintegrosProveedorAnulados")
                        .HasForeignKey("UsuarioAnulacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.Usuario", "Usuario")
                        .WithMany("ReintegrosProveedor")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("Compra");

                    b.Navigation("Empresa");

                    b.Navigation("MedioPago");

                    b.Navigation("TurnoCaja");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioAnulacion");
                });

            modelBuilder.Entity("saas.Models.ReintegroVenta", b =>
                {
                    b.HasOne("saas.Models.Caja", "Caja")
                        .WithMany()
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithMany("ReintegrosVenta")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.MedioPago", "MedioPago")
                        .WithMany("ReintegrosVenta")
                        .HasForeignKey("MedioPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.TurnoCaja", "TurnoCaja")
                        .WithMany()
                        .HasForeignKey("TurnoCajaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.Usuario", "UsuarioAnulacion")
                        .WithMany("ReintegrosVentaAnulados")
                        .HasForeignKey("UsuarioAnulacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.Usuario", "Usuario")
                        .WithMany("ReintegrosVenta")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Venta", "Venta")
                        .WithMany("ReintegrosVenta")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("Empresa");

                    b.Navigation("MedioPago");

                    b.Navigation("TurnoCaja");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioAnulacion");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("saas.Models.TransferenciaCaja", b =>
                {
                    b.HasOne("saas.Models.Caja", "CajaDestino")
                        .WithMany("TransferenciasDestino")
                        .HasForeignKey("CajaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Caja", "CajaOrigen")
                        .WithMany("TransferenciasOrigen")
                        .HasForeignKey("CajaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithMany("TransferenciasCaja")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.TurnoCaja", "TurnoCaja")
                        .WithMany()
                        .HasForeignKey("TurnoCajaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.Usuario", "UsuarioAnulacion")
                        .WithMany("TransferenciasCajaAnuladas")
                        .HasForeignKey("UsuarioAnulacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("saas.Models.Usuario", "Usuario")
                        .WithMany("TransferenciasCaja")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CajaDestino");

                    b.Navigation("CajaOrigen");

                    b.Navigation("Empresa");

                    b.Navigation("TurnoCaja");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioAnulacion");
                });

            modelBuilder.Entity("saas.Models.TurnoCaja", b =>
                {
                    b.HasOne("saas.Models.Caja", "Caja")
                        .WithMany("TurnosCaja")
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithMany("TurnosCaja")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Usuario", "UsuarioApertura")
                        .WithMany("TurnosCajaApertura")
                        .HasForeignKey("UsuarioAperturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("saas.Models.Usuario", "UsuarioCierre")
                        .WithMany("TurnosCajaCierre")
                        .HasForeignKey("UsuarioCierreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Caja");

                    b.Navigation("Empresa");

                    b.Navigation("UsuarioApertura");

                    b.Navigation("UsuarioCierre");
                });

            modelBuilder.Entity("saas.Models.Usuario", b =>
                {
                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("saas.Models.Venta", b =>
                {
                    b.HasOne("saas.Models.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("saas.Models.Empresa", "Empresa")
                        .WithMany("Ventas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("saas.Models.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("saas.Models.Caja", b =>
                {
                    b.Navigation("CajaMediosPago");

                    b.Navigation("MovimientosCaja");

                    b.Navigation("TransferenciasDestino");

                    b.Navigation("TransferenciasOrigen");

                    b.Navigation("TurnosCaja");
                });

            modelBuilder.Entity("saas.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("saas.Models.CategoriaGasto", b =>
                {
                    b.Navigation("MovimientosCaja");
                });

            modelBuilder.Entity("saas.Models.Cliente", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("saas.Models.CobroVenta", b =>
                {
                    b.Navigation("MovimientoCaja");
                });

            modelBuilder.Entity("saas.Models.Compra", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("DevolucionesCompra");

                    b.Navigation("MovimientosStock");

                    b.Navigation("PagosProveedor");

                    b.Navigation("ReintegrosProveedor");
                });

            modelBuilder.Entity("saas.Models.DetalleCompra", b =>
                {
                    b.Navigation("DetallesDevolucion");
                });

            modelBuilder.Entity("saas.Models.DevolucionCompra", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("MovimientosStock");
                });

            modelBuilder.Entity("saas.Models.Empresa", b =>
                {
                    b.Navigation("Cajas");

                    b.Navigation("Categorias");

                    b.Navigation("CategoriasGasto");

                    b.Navigation("Clientes");

                    b.Navigation("CobrosVenta");

                    b.Navigation("Compras");

                    b.Navigation("Configuracion");

                    b.Navigation("MediosPago");

                    b.Navigation("MovimientosCaja");

                    b.Navigation("MovimientosStock");

                    b.Navigation("PagosProveedor");

                    b.Navigation("Productos");

                    b.Navigation("Proveedores");

                    b.Navigation("ReintegrosProveedor");

                    b.Navigation("ReintegrosVenta");

                    b.Navigation("TransferenciasCaja");

                    b.Navigation("TurnosCaja");

                    b.Navigation("Usuarios");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("saas.Models.MedioPago", b =>
                {
                    b.Navigation("CajaMediosPago");

                    b.Navigation("CobrosVenta");

                    b.Navigation("MovimientosCaja");

                    b.Navigation("PagosProveedor");

                    b.Navigation("ReintegrosProveedor");

                    b.Navigation("ReintegrosVenta");
                });

            modelBuilder.Entity("saas.Models.MovimientoCaja", b =>
                {
                    b.Navigation("Reversiones");
                });

            modelBuilder.Entity("saas.Models.PagoProveedor", b =>
                {
                    b.Navigation("MovimientoCaja");
                });

            modelBuilder.Entity("saas.Models.Producto", b =>
                {
                    b.Navigation("DetallesCompra");

                    b.Navigation("DetallesVenta");

                    b.Navigation("MovimientosStock");
                });

            modelBuilder.Entity("saas.Models.Proveedor", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("saas.Models.ReintegroProveedor", b =>
                {
                    b.Navigation("MovimientoCaja");
                });

            modelBuilder.Entity("saas.Models.ReintegroVenta", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("MovimientoCaja");

                    b.Navigation("MovimientosStock");
                });

            modelBuilder.Entity("saas.Models.TransferenciaCaja", b =>
                {
                    b.Navigation("MovimientosCaja");
                });

            modelBuilder.Entity("saas.Models.TurnoCaja", b =>
                {
                    b.Navigation("MovimientosCaja");
                });

            modelBuilder.Entity("saas.Models.Usuario", b =>
                {
                    b.Navigation("CobrosVenta");

                    b.Navigation("CobrosVentaAnulados");

                    b.Navigation("Compras");

                    b.Navigation("ComprasAnuladas");

                    b.Navigation("MovimientosCaja");

                    b.Navigation("MovimientosStock");

                    b.Navigation("PagosProveedor");

                    b.Navigation("PagosProveedorAnulados");

                    b.Navigation("ReintegrosProveedor");

                    b.Navigation("ReintegrosProveedorAnulados");

                    b.Navigation("ReintegrosVenta");

                    b.Navigation("ReintegrosVentaAnulados");

                    b.Navigation("TransferenciasCaja");

                    b.Navigation("TransferenciasCajaAnuladas");

                    b.Navigation("TurnosCajaApertura");

                    b.Navigation("TurnosCajaCierre");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("saas.Models.Venta", b =>
                {
                    b.Navigation("CobrosVenta");

                    b.Navigation("Detalles");

                    b.Navigation("MovimientosStock");

                    b.Navigation("ReintegrosVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
